<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Credit Card Number</name>
   <tag></tag>
   <elementGuidId>c83894ee-5faf-440b-ba91-63a1f5ec8136</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#creditCardNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'creditCardNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e39ec68-158c-4d23-ba06-72fa727fcaf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b97bcdec-6d0e-4b10-a05b-3b98c6f0b7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creditCardNumber</value>
      <webElementGuid>5360d7bd-e40c-4c55-95a1-8469603a692f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>creditCardNumber</value>
      <webElementGuid>6d20e268-2f4e-4934-a849-1a49a794a9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Credit Card Number</value>
      <webElementGuid>3c1a5366-1d14-4b7b-81d0-0c884a874852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-74406f2b362234db7c17f0aa36cb5455</value>
      <webElementGuid>ecff6c24-6fe4-4b07-a003-62dec430385e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'creditCardNumber']</value>
      <webElementGuid>84889eb1-d975-4da9-bf15-79c9f3ece9de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'creditCardNumber']</value>
      <webElementGuid>c9a8bc08-1ae7-4588-9448-20ad18a0ad82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'creditCardNumber' and @name = 'creditCardNumber' and @placeholder = 'Credit Card Number']</value>
      <webElementGuid>4a67092a-4cf3-49d9-8ad0-5a478b37503a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
