<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_12345</name>
   <tag></tag>
   <elementGuidId>e0a82ff1-fd89-4f12-bd95-a6b5e8cab40c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zipCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'zipCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fa9d0f6-ecd1-4d93-8ee9-c23a6264db4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0bec798-24af-409a-a33f-01cd28dca87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zipCode</value>
      <webElementGuid>bcffc666-08e3-4713-a8de-785ff12ac940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zipCode</value>
      <webElementGuid>58e11df4-167c-4fed-97d6-1231627ea1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>12345</value>
      <webElementGuid>118eb651-f778-44e8-8dc2-7ee2613a2e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e7bbafe3b138ba71913b00c414a0cbe9</value>
      <webElementGuid>c8fde152-a84c-480b-9f29-dc13c23a5e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'zipCode']</value>
      <webElementGuid>38c324c1-dde8-49b8-bc51-8e40af818877</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'zipCode']</value>
      <webElementGuid>1810662e-3680-4f15-97b3-549307c210ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'zipCode' and @id = 'zipCode' and @placeholder = '12345']</value>
      <webElementGuid>0f3d7f79-e3ad-43ac-9565-86c3a5203b42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
