<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_John Smith</name>
   <tag></tag>
   <elementGuidId>2b569f74-3cbc-43c5-be1a-366096d1e99d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nameOnCard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'nameOnCard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>525dca12-c3b6-4511-8662-fa45ec53be50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>183b7b54-c3ef-48a8-be20-d6504d0aab25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nameOnCard</value>
      <webElementGuid>97306b64-d5c9-40e4-b588-36e34f386cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>John Smith</value>
      <webElementGuid>8594fbfc-6810-4880-b860-386542b0667a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nameOnCard</value>
      <webElementGuid>cf99893d-a3cf-4d64-8229-c056faa95fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-74aeb0be66cee1ac4dcdde66653ae163</value>
      <webElementGuid>e653c965-caea-4fe1-9858-e570a520d79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'nameOnCard']</value>
      <webElementGuid>ff683bd3-bedf-4953-9c9a-5ca9ad8b9ee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'nameOnCard']</value>
      <webElementGuid>597b280c-cbe8-4169-bc5d-9ba951ea0fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nameOnCard' and @placeholder = 'John Smith' and @name = 'nameOnCard']</value>
      <webElementGuid>31d8ca87-baa8-4a2d-a481-c54ddb15332c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
