<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_1, Wednesday, April 2026. Available Selec_1</name>
   <tag></tag>
   <elementGuidId>64a408f6-a5f3-4417-9a70-c07710c11397</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;\31 \,\ Wednesday\,\ April\ 2026\.\ Available\ Select\ as\ check-in\ date\.&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = '1, Wednesday, April 2026. Available Select as check-in date.']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b2a1ac31-8aea-44b6-8c9e-74f77e1af263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ae3144f0-81c9-4d14-a223-7ca31c0c8dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>1, Wednesday, April 2026. Available Select as check-in date.</value>
      <webElementGuid>e0bc1e22-8bfa-41b0-8335-4649a07c0f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d1j0q1s5 atm_vy_1osqo2v atm_1w_1qhzids atm_mk_h2mmj6 atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1h6ojuz atm_fb_1cl4t0h atm_c8_dlk8xv atm_cs_1mexzig atm_7l_1dmvgf5 atm_9j_tlke0l atm_vb_glywfm atm_70_glywfm atm_2d_n7od8j atm_3f_n7od8j atm_lb_n7od8j atm_lh_n7od8j atm_vy_1sywq1v_vmtskl atm_e2_1osqo2v_vmtskl atm_mk_stnw88_vmtskl atm_92_1yyfdc7_vmtskl atm_5j_1ssbidh_vmtskl atm_wq_1mrwo0b_vmtskl atm_70_1r365bk_1rqz0hn_uv4tnr atm_kd_glywfm_1w3cfyq atm_3f_glywfm_e4a3ld atm_l8_idpfg4_e4a3ld atm_gi_idpfg4_e4a3ld atm_3f_glywfm_1r4qscq atm_kd_glywfm_6y7yyg atm_uc_1wx0j5_9xuho3 atm_70_a4f9pl_9xuho3 atm_uc_glywfm_9xuho3_1rrf6b5 undefined dir dir-ltr</value>
      <webElementGuid>35191391-4126-454b-a440-cabacad15741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state--date-string</name>
      <type>Main</type>
      <value>2026-04-01</value>
      <webElementGuid>d043434d-b6d3-4ddf-bb7c-1e2dc1bba523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>12a695bf-56c5-4db6-ae60-04aec5b6409d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c0601223-975d-412e-9efa-4b5ca7245641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fdc902c558c9fb3a8747de485e370c5a</value>
      <webElementGuid>a1da2018-0606-45e4-9111-40ef5fdbb2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = '1, Wednesday, April 2026. Available Select as check-in date.']</value>
      <webElementGuid>85ad7e15-7036-447c-9e6c-a8ab580363b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = '1, Wednesday, April 2026. Available Select as check-in date.']</value>
      <webElementGuid>7011314a-58bf-4375-97b0-3f5888615dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '1' or . = '1')]</value>
      <webElementGuid>ef1cac8a-6d6d-4bc7-b0dd-7f5e0fc90408</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
