<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_path</name>
   <tag></tag>
   <elementGuidId>62bec821-4304-4a9c-bdf1-50f236392179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;stepper-adults-increase-button&quot;] path</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid = 'stepper-adults-increase-button']//path</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'stepper-adults-increase-button']//path</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>bc99e24e-6efb-4838-bfad-9d9562e3469c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>m6.75.75v4.5h4.5v1.5h-4.5v4.5h-1.5v-4.5h-4.5v-1.5h4.5v-4.5z</value>
      <webElementGuid>5606ff97-bb5b-4a03-b369-f0c714d3acd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1b87880c7da1cd85b48d14722f064be8</value>
      <webElementGuid>3d0ceec7-370c-46d7-8751-69a033d9a0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'stepper-adults-increase-button']//path</value>
      <webElementGuid>2afd35e4-a609-4d0f-a117-3a15a25ae9e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'stepper-adults-increase-button']//path</value>
      <webElementGuid>4ca5e073-1f94-42a1-89e8-f4b058ebc358</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
