<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_presentation</name>
   <tag></tag>
   <elementGuidId>45bb8387-8863-48f5-b2e8-d213ea11d6d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Choose\ a\ language\ and\ currency&quot;] [focusable=&quot;false&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@aria-label = 'Choose a language and currency']//*[@focusable = 'false']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Choose a language and currency']//*[@focusable = 'false']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>2a32962e-8808-47ad-ac36-1295bcf43133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>8f05893e-e8b2-401d-b6aa-7ed85aa7c391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 16 16</value>
      <webElementGuid>beb60729-f943-4b76-a5c8-4c7681af94b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f856eba1-9281-47a4-87e2-56af319ab282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>859c12d6-e721-4f22-acb8-58dba5a13c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8ec92b86-de8a-4306-81ce-5947ec0ee47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-09e6c5e868395772a9bcb2aa80055fe8</value>
      <webElementGuid>e55bb487-7e62-4e64-9a6d-838940d3af55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Choose a language and currency']//*[@focusable = 'false']</value>
      <webElementGuid>20a0bb29-f06a-4c55-8c4e-58150b444199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Choose a language and currency']//*[@focusable = 'false']</value>
      <webElementGuid>a34eb451-b0d4-4197-b37c-2e4e99c10920</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
