<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_registeruser</name>
   <tag></tag>
   <elementGuidId>d31e1679-d4f2-47f5-aca8-510e42abc489</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'registeruser']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;registeruser&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8e8942d0-9ec4-406f-a6d1-28ebb9119961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://vinothqaacademy.com/demo-site/</value>
      <webElementGuid>9f77945f-d1a3-4b2a-befe-e24c267dcd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registeruser</value>
      <webElementGuid>5c0a7bf4-08aa-465b-ac70-87eb38687b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Registration Form</value>
      <webElementGuid>c197960a-cee1-4325-af9f-c4044c39f900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-34f1a191771744f985100af7f9602839</value>
      <webElementGuid>ff6691cc-e1c7-4894-bfbf-e710f419a34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'registeruser']</value>
      <webElementGuid>2f0499bb-d53d-4428-b59b-90ed24d94624</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'registeruser']</value>
      <webElementGuid>c5f3816a-e147-4af6-b97b-e0b22d2d344e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://vinothqaacademy.com/demo-site/' and @name = 'registeruser' and @title = 'Registration Form']</value>
      <webElementGuid>28ac08d1-13ab-455e-ac89-7496b1698705</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
