<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_employeetable</name>
   <tag></tag>
   <elementGuidId>9c709ff9-0850-400c-a4d9-5737810e2997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'employeetable']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;employeetable&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b30fe3f7-8765-4984-8799-9ceeefaf86f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://vinothqaacademy.com/webtable/</value>
      <webElementGuid>97061fe1-86a3-4d2b-8992-b82a98177770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>employeetable</value>
      <webElementGuid>b426cf19-7f69-4179-b7f7-dad956ed7757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Web Table</value>
      <webElementGuid>e3eb43b3-1171-423f-a288-8c6edeb568c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-920dfcd7e8247484ff10e9becfe4a899</value>
      <webElementGuid>43d97ba0-a7d0-4693-be6a-770d39a300b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'employeetable']</value>
      <webElementGuid>2d8c8796-a180-426e-916a-9cea22ebdac4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'employeetable']</value>
      <webElementGuid>147442a1-0c32-4703-9c88-8172e5084ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://vinothqaacademy.com/webtable/' and @name = 'employeetable' and @title = 'Web Table']</value>
      <webElementGuid>3222de9d-934e-41e8-9cb5-3ed6101ac3a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
