<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_popuppage</name>
   <tag></tag>
   <elementGuidId>c6230e35-73cd-4254-b9bc-a7a5e337c203</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'popuppage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;popuppage&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>27ace0b6-de62-4f4b-9831-ec215a0e4e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://vinothqaacademy.com/alert-and-popup/</value>
      <webElementGuid>af21498a-d9e9-4c6c-8dc3-6199a117bc2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popuppage</value>
      <webElementGuid>15829c21-4454-47fd-8aee-dd6421a055cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Alert &amp; Popup</value>
      <webElementGuid>ba36c64d-9f35-4716-bf90-ee72a9a1e379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8ed96103abc1bfbba5c775dd60bedcfc</value>
      <webElementGuid>120a439a-c547-4086-8ef7-1325e35124df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'popuppage']</value>
      <webElementGuid>be2391ca-df54-4fdb-8bfc-63f310289f27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'popuppage']</value>
      <webElementGuid>0b4989ec-acd2-40e0-9758-420393de936a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://vinothqaacademy.com/alert-and-popup/' and @name = 'popuppage' and @title = 'Alert &amp; Popup']</value>
      <webElementGuid>fd4474bf-ded7-4c64-a89f-93a780770961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
