<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Package</name>
   <tag></tag>
   <elementGuidId>3259d54e-3870-4107-b3ea-5f8cbabffb5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(name() = 'li') and (position() = 2)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(2)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Package' or . = 'Package')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0d1a137d-ea43-4207-aa00-1301fe64320a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Package</value>
      <webElementGuid>afdb1c97-9956-4df6-893b-ad4f9b1b1de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a370075346c8831bfaa99d7d72b1db39</value>
      <webElementGuid>f40eef79-ac6e-4db4-88da-6df42b0d42c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'li') and (position() = 2)]</value>
      <webElementGuid>12abb9c7-8f1e-461c-9bcb-730e68364b35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'li') and (position() = 2)]</value>
      <webElementGuid>266fba97-6ca7-46a8-b1a9-b8d4bddef5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Package' or . = 'Package')]</value>
      <webElementGuid>53e66f7b-b8d9-45fb-93d9-afa2207b7069</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
