<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Over 1,000 homes in Brisbane</name>
   <tag></tag>
   <elementGuidId>11b08d2b-f52f-4c26-bf5d-a35bcffbda8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;stays-page-heading&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'stays-page-heading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>340cd647-40ee-4f1f-b426-a8de18d6e2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ttkzbcj atm_fr_i8y2z4 atm_cs_1madr4d atm_c8_1k92wuq atm_g3_1k8s52q dir dir-ltr</value>
      <webElementGuid>7c4cfe61-202d-4857-8051-e13c60d26eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>80fa4567-3dcd-44f9-9400-0ab197d3dcaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>stays-page-heading</value>
      <webElementGuid>08ddfdd3-e32c-43ff-b1a4-9b7f8b25107e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Over 1,000 homes in Brisbane</value>
      <webElementGuid>8c0841c5-4abc-466b-a14a-cb03ef23b058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1e54778e393c8198827f50fee6d2f0e6</value>
      <webElementGuid>e7696f99-39ac-47db-89d8-f17f6fc4db47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'stays-page-heading']</value>
      <webElementGuid>c0117980-1b8c-4112-bf6b-ef48a19b2b4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'stays-page-heading']</value>
      <webElementGuid>a85ba113-9ee9-42f3-adc4-ba31e381fcb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Over 1,000 homes in Brisbane' or . = 'Over 1,000 homes in Brisbane')]</value>
      <webElementGuid>fe17f9fd-b0b3-4d5b-a817-d5fbfdc09c47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
